print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/Jubie/Documents/Parsons_Fall-2014/PSAM_5600-B-BuildingWorlds/Unity/tenPrintHw/Assets/bldgblck.ma"`)
{		
	file -o "/Users/Jubie/Documents/Parsons_Fall-2014/PSAM_5600-B-BuildingWorlds/Unity/tenPrintHw/Assets/bldgblck.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Jubie/Documents/Parsons_Fall-2014/PSAM_5600-B-BuildingWorlds/Unity/tenPrintHw/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/Jubie/Documents/Parsons_Fall-2014/PSAM_5600-B-BuildingWorlds/Unity/tenPrintHw/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/Jubie/Documents/Parsons_Fall-2014/PSAM_5600-B-BuildingWorlds/Unity/tenPrintHw/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
